import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BackgroundImage from "../components/BackgroundImage";
import Hero from "../components/Hero";
import TodaysUpdate from "../components/TodaysUpdate";
// import Logo from "../assets/Logo.svg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Crimson Crashers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./Logo.svg" />
      </Head>

      <BackgroundImage />

      {/* Hero */}
      <Hero />
      {/* Today's Update */}
      <TodaysUpdate />
    </div>
  );
};

export default Home;
